# Fast test builds to smoke test that nothing's broken
# (without codesign, notarization, publish artifacts)
name: Build test

# Run workflow for {action} on all branches, except...
on:
  push:
    branches-ignore:
      - master # Ignore master branch, since that is covered by the release workflow
  pull_request:
    branches-ignore:
      - master # Ignore master branch, since that is covered by the release workflow

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest] # The operating systems to build for
        node: [12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2 # See: https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node }}

      # ----- Yarn Install and Caching ------
      # Cache Yarn 2
      # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
      # ----- / Yarn Install and Caching ------

      # ----- electron-nuxt ------
      - name: Build/release Electron app
        uses: ./.github/actions/action-electron-builder
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          # type: string
          github_token: ${{ secrets.github_token }}

          # Never release
          release: false

          # Mac certificate info
          mac_certs: ${{ secrets.CSC_LINK }}
          mac_certs_password: ${{ secrets.CSC_KEY_PASSWORD }}
        env:
          # macOS notarization
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      # ----- / electron-nuxt ------
